version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - /tmp/mysqldb:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: flamingo
      MYSQL_DATABASE: formfactor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
